version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: hashids
    versions:
    - 2.0.4
